### ISSUE TITLE
Problem with identifing the old functions in the newest version

### ISSUE THREAD

**Issue by DavidOldAccount** [byteandahalf/MCPE-NativeMods#5]
Hello!
There are many functions which can be identified in the version before 0.13.0 are shown as "sub_xxxx" in the newest iOS version( like "item::"  ). How can I deal with it? Can the new version still accept the old functions which are stripped ( item:: functions are now shown as sub_xxx etc. ). Thanks a lot :)

**Comment by byteandahalf** [comment]
What you're referring to is one of the biggest difficulties with modding iOS: the symbols are stripped. It obviously won't still accept the functions, so to mod it you need to manually find the addresses and slide with ASLR (both of which are very difficult and I'm not prepared to tell you how, you need to learn about assembly) github.com/byteandahalf/PocketPower-iOS has an overcomplicated example of an iOS mod if you're interested, but the addresses are all for 0.12.1

**Comment by byteandahalf** [comment]
Symbols have always been stripped for iOS, except that Mojang accidentally didn't strip them in iOS 0.12.2, which is what I think you're seeing.

**Comment by DavidOldAccount** [comment]
May I have your email or something else? I guess I found a way to identify those sub_xxx to the origin functions, I have some screenshots but I can not send it here. Also can the old parameters still be used in the stripped functions?
Thx a lot. And the reason why we stick on your wiki is that no one else can tell us how to modificate minecraftpe ios.
