### ISSUE TITLE
Help with Dimension

### ISSUE THREAD

**Issue by rekmolly** [byteandahalf/MCPE-NativeMods#7]
Hi! I try make custom dimension, but getting crash game.

Why is code dosent work?
static std::unique_ptr<Dimension> (*Dimension$createNew_real)(DimensionId, Level &);
static std::unique_ptr<Dimension> Dimension$createNew_hook(DimensionId id, Level &level)
{
    if(id == DimensionId::DIMENSION_NEW)
        return std::unique_ptr<Dimension>(new NewDimension(level));

```
return Dimension$createNew_real(id, level);
```

}

I also tried to specify the type of generator is its measurement but get an error in my code:
std::unique_ptr<ChunkSource> NewDimension::_createGenerator(GeneratorType type){

```
    return GeneratorType::FLAT
```

}

**Comment by byteandahalf** [comment]
Do you have a crash log?

**Comment by rekmolly** [comment]
Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc42ce750 in tid 18202 (Main Thread)
    r0 65282d00  r1 00000044  r2 c42ce748  r3 4790ff3e
    r4 61cf87f0  r5 4790ff1c  r6 00000080  r7 42516bd3
    r8 61cf87bc  r9 65282d94  sl 648b67da  fp 4790ff1c
    ip 6142ab00  sp 61cf8738  lr 6109b12f  pc 60c3ce18  cpsr 680f0030
  #00  pc 0005ee18  /mnt/asec/com.mojang.minecraftpe-2/lib/libgnustl_shared.so (std::_Rb_tree_increment(std::_Rb_tree_node_base const_)+7)
  #01  pc 002b812b  /data/data/net.zhuoweizhang.mcpelauncher.pro/app_patched/libminecraftpe_text_section (deleted) (PortalForcer::findPortal(DimensionId, BlockPos const&, int, BlockPos&) const+222)
  #02  pc 003584af  /data/data/net.zhuoweizhang.mcpelauncher.pro/app_patched/libminecraftpe_text_section (deleted) (Level::_playerChangeDimension(Player_, ChangeDimensionRequest&)+1342)
  #03  pc 003587c1  /data/data/net.zhuoweizhang.mcpelauncher.pro/app_patched/libminecraftpe_text_section (deleted) (Level::_handleChangeDimensionRequests()+60)
  #04  pc 00358acd  /data/data/net.zhuoweizhang.mcpelauncher.pro/app_patched/libminecraftpe_text_section (deleted) (Level::requestPlayerChangeDimension(Player&, std::unique_ptr<ChangeDimensionRequest, std::default_delete<ChangeDimensionRequest> >)+180)
  #05  pc 004c359d  /data/data/net.zhuoweizhang.mcpelauncher.pro/app_patched/libminecraftpe_text_section (deleted) (LocalPlayer::changeDimension(DimensionId)+164)
  #06  pc 0000345d  /data/app-lib/com.ksymc.newdimension-1/libcom.ksymc.newdimension.so (ExampleItem::useOn(ItemInstance_, Player_, int, int, int, signed char, float, float, float)+12)
  #07  pc 004afd43  /data/data/net.zhuoweizhang.mcpelauncher.pro/app_patched/libminecraftpe_text_section (deleted) (ItemInstance::useOn(Player_, int, int, int, signed char, float, float, float)+46)
  #08  pc 0042550b  /data/data/net.zhuoweizhang.mcpelauncher.pro/app_patched/libminecraftpe_text_section (deleted) (GameMode::useItemOn(Player&, ItemInstance_, BlockPos const&, signed char, Vec3 const&)+422)
  #09  pc 00047427  /data/app-lib/io.mrarm.mctoolbox-1/libmod.so
  #10  pc 0042067d  /data/data/net.zhuoweizhang.mcpelauncher.pro/app_patched/libminecraftpe_text_section (deleted) (GameMode::buildBlock(Player&, BlockPos, signed char)+52)
  #11  pc 00420615  /data/data/net.zhuoweizhang.mcpelauncher.pro/app_patched/libminecraftpe_text_section (deleted) (GameMode::startBuildBlock(Player&, BlockPos, signed char)+28)
  #12  pc 00321439  /data/data/net.zhuoweizhang.mcpelauncher.pro/app_patched/libminecraftpe_text_section (deleted) (MinecraftClient::handleBuildAction(BuildActionIntention&)+640)
  #13  pc 003218f9  /data/data/net.zhuoweizhang.mcpelauncher.pro/app_patched/libminecraftpe_text_section (deleted) (MinecraftClient::handleBuildOrAttackButtonPress()+16)
  #14  pc 0028c96b  /data/data/net.zhuoweizhang.mcpelauncher.pro/app_patched/libminecraftpe_text_section (deleted) (InputHandler::handleButtonEvent(ButtonEventData const&)+202)
  #15  pc 0029ef6d  /data/data/net.zhuoweizhang.mcpelauncher.pro/app_patched/libminecraftpe_text_section (deleted) (InputHandler::tick()+924)
  #16  pc 303a302c  <unknown>
